# -*- coding: utf-8 -*-
"""Regression_random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8E1ONUm-D9f9sYepzNX9n9tcvSoPr_W

# Regresion Random Forest

## Etape 1 : Chargement des Bibliothèques
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Etape 2 : Chargement des données"""

dataset = pd.read_csv('Position_Salaries.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""## Etape 3 : Entrainer le modèle de regression Random Forest"""

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x, y)

"""## Etape 4 : Prédire un résultat """

regressor.predict([[6.5]])

"""## Etape 5 : Visualisation de la regression Random Forest"""

x_grid = np.arange(min(x), max(x), 0.1)
x_grid = x_grid.reshape((len(x_grid), 1))
plt.scatter(x, y, color = 'red')
plt.plot(x_grid, regressor.predict(x_grid), color = 'blue')
plt.title('Regression Random Forest')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()